# Generated by Django 5.0.14 on 2025-11-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealorder',
            unique_together={('employee', 'order_date', 'meal_type')},
        ),
    ]
