# Generated by Django 5.0.14 on 2025-11-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_mealorder_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorder',
            name='location',
            field=models.CharField(choices=[('budaiya', 'Budaiya'), ('khamis', 'Khamis'), ('gharbiya', 'Gharbiya')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
