# Generated by Django 5.0.14 on 2025-11-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_mealorder_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorder',
            name='duty_type',
            field=models.CharField(blank=True, choices=[('24h', '٢٤ ساعة'), ('dbl_5_7', 'دبل إضافي (٥–٧ ص)'), ('dbl_8_13', 'دبل إضافي (٨ ص–١ م)'), ('dbl_14_20', 'دبل إضافي (٢–٨ م)'), ('8h_morn', 'دوام ٨ ساعات (صباحي)'), ('8h_noon', 'دوام ٨ ساعات (مسائي)'), ('8h_night', 'دوام ٨ ساعات (ليلي)'), ('12h_day', 'دوام ١٢ ساعة (٥ ص–٥ م)'), ('12h_night', 'دوام ١٢ ساعة (٥ م–٥ ص)')], max_length=20, null=True, verbose_name='نوع الدوام'),
        ),
        migrations.AlterField(
            model_name='mealorder',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealorder',
            name='meal_type',
            field=models.CharField(max_length=20),
        ),
    ]
