# Generated by Django 5.0.14 on 2025-11-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_mealorder_duty_type_alter_mealorder_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Saturday', 'السبت'), ('Sunday', 'الأحد'), ('Monday', 'الاثنين'), ('Tuesday', 'الثلاثاء'), ('Wednesday', 'الأربعاء'), ('Thursday', 'الخميس'), ('Friday', 'الجمعة')], max_length=10, unique=True, verbose_name='اليوم')),
                ('breakfast_text', models.CharField(blank=True, max_length=200, verbose_name='فطور')),
                ('lunch_text', models.CharField(blank=True, max_length=200, verbose_name='غداء')),
                ('dinner_text', models.CharField(blank=True, max_length=200, verbose_name='عشاء')),
            ],
        ),
    ]
